const cache = new Map(), inFlight = new Map();
const CACHE_MS = 15 * 60 * 1000;
let ebayToken = null;

const colors = ["Black", "White", "Blue", "Red", "Green", "Silver", "Gold", "Gray", "Pink", "Brown", "Natural wood"];
const materials = ["Solid wood", "Engineered wood", "Wood", "Glass", "Marble", "Stone", "Ceramic", "Metal", "Plastic", "Leather", "Steel", "Aluminum", "Cotton"];
const features = ["Wireless", "Bluetooth", "Waterproof", "Rechargeable", "Smart", "Portable", "Noise cancelling", "Organic", "Silent"];

function number(value) { if (typeof value === "number" && Number.isFinite(value)) return value; const parsed = Number.parseFloat(String(value ?? "").replace(/[^0-9.]/g, "")); return Number.isFinite(parsed) ? parsed : null; }
function includesPhrase(text, value) { return new RegExp(`(?:^|[^a-z0-9])${value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&").replace(/[- ]/g, "[- ]")}(?:$|[^a-z0-9])`, "i").test(text); }
function inferValue(text, values) { return values.find((value) => includesPhrase(text, value)); }
function inferNumberBucket(text, pattern, buckets) { const value = number(text.match(pattern)?.[1]); return value === null ? undefined : buckets.find(([max]) => value <= max)?.[1]; }
function inferTableSize(text) { const seats = text.match(/(?:seats?|for)\s*(\d+)|(?:^|\D)(\d+)\s*(?:person|people|seater)/i); const count = number(seats?.[1] ?? seats?.[2]); if (count !== null) return count <= 2 ? "2 seats" : count <= 4 ? "4 seats" : count <= 6 ? "6 seats" : "8+ seats"; return inferNumberBucket(text, /(?:^|\D)(\d{2,3}(?:\.\d+)?)\s*(?:in(?:ch(?:es)?)?|")/i, [[47, "Compact (under 48 in)"], [71, "Standard (48–71 in)"], [Infinity, "Large (72+ in)"]]); }
function inferChairs(text) { return /(?:with|includes?)\s+(?:\d+\s+)?chairs?|table\s*(?:&|and)\s*(?:\d+\s+)?chairs?|dining\s+set|\d+[- ]piece/i.test(text) ? "Includes chairs" : /dining\s+table|table only/i.test(text) ? "Table only" : undefined; }
function inferExtendable(text) { return /extendable|extending|extension|expandable|drop[- ]leaf|butterfly[- ]leaf/i.test(text) ? "Extendable" : /dining\s+table/i.test(text) ? "Fixed" : undefined; }
function inferScreen(text) { const match = text.match(/\b(\d{1,3}(?:\.\d+)?)\s*(?:in(?:ch(?:es)?)?|")/i); return match ? `${match[1]} in` : undefined; }
function inferStorage(text, qualifier = "") { const pattern = qualifier ? new RegExp(`\\b(\\d+)\\s*(GB|TB)\\s+${qualifier}\\b`, "i") : /\b(\d+)\s*(GB|TB)\b/i; const match = text.match(pattern); return match ? `${match[1]} ${match[2].toUpperCase()}` : undefined; }
function inferShoeSize(text) { const match = text.match(/(?:size|US)\s*(\d{1,2}(?:\.5)?)/i); return match ? `US ${match[1]}` : undefined; }

const productRules = [
  { match: /dining\s+(?:table|set)/i, rules: [{ id: "tableSize", label: "Size / seats", infer: inferTableSize }, { id: "material", label: "Material", values: materials }, { id: "shape", label: "Shape", values: ["Rectangular", "Round", "Oval", "Square"] }, { id: "chairsIncluded", label: "Chairs included", infer: inferChairs }, { id: "extendable", label: "Extendable", infer: inferExtendable }] },
  { match: /clock/i, rules: [{ id: "clockType", label: "Clock type", values: ["Wall clock", "Alarm clock", "Desk clock", "Smart clock", "Mantel clock"] }, { id: "movement", label: "Movement", values: ["Quartz", "Digital", "Mechanical", "Atomic"] }] },
  { match: /coffee|espresso/i, rules: [{ id: "type", label: "Coffee maker type", values: ["Drip", "Espresso", "Pod", "Single serve", "Cold brew", "French press"] }] },
  { match: /shoes?|sneakers?|boots?/i, rules: [{ id: "activity", label: "Activity", values: ["Running", "Trail", "Walking", "Hiking", "Basketball", "Training"] }, { id: "shoeSize", label: "Size", infer: inferShoeSize }] },
  { match: /laptop|notebook|chromebook/i, rules: [{ id: "platform", label: "Platform", values: ["Windows", "MacBook", "Chromebook", "Gaming"] }, { id: "screenSize", label: "Screen size", infer: inferScreen }, { id: "memory", label: "Memory", infer: (text) => inferStorage(text, "RAM") }, { id: "storage", label: "Storage", infer: inferStorage }] },
  { match: /phone|smartphone/i, rules: [{ id: "network", label: "Network", values: ["Unlocked", "5G", "Dual SIM", "Prepaid"] }, { id: "storage", label: "Storage", infer: inferStorage }, { id: "screenSize", label: "Screen size", infer: inferScreen }] },
  { match: /camera|lens/i, rules: [{ id: "cameraType", label: "Camera type", values: ["Mirrorless", "DSLR", "Instant", "Action", "Digital", "Film"] }] },
  { match: /vacuum/i, rules: [{ id: "vacuumType", label: "Vacuum type", values: ["Robot", "Cordless", "Upright", "Canister", "Handheld"] }, { id: "features", label: "Features", values: features }] },
  { match: /(?:television|\btv\b|monitor)/i, rules: [{ id: "screenSize", label: "Screen size", infer: inferScreen }, { id: "displayType", label: "Display", values: ["OLED", "QLED", "Mini-LED", "LED", "LCD"] }, { id: "resolution", label: "Resolution", values: ["8K", "4K", "1440p", "1080p"] }] },
  { match: /(?:office|coffee|side|console)\s+table|chair|desk|sofa|couch/i, rules: [{ id: "material", label: "Material", values: materials }, { id: "shape", label: "Shape", values: ["Rectangular", "Round", "Oval", "Square"] }] },
];
const storeRules = [
  [/clock|watch/i, ["clock", "watch", "home goods", "furniture", "antique", "gift", "department", "electronics"]],
  [/headphones?|earbuds?|speaker|audio/i, ["audio", "electronics", "computer", "department", "appliance", "music"]],
  [/shoes?|sneakers?|boots?|sandals?/i, ["shoe", "sporting goods", "department", "clothing", "outdoor"]],
  [/coffee|espresso|kettle|toaster|blender/i, ["appliance", "kitchen", "home goods", "department", "coffee"]],
  [/laptop|computer|keyboard|mouse|monitor|printer/i, ["computer", "electronics", "office supply", "department"]],
  [/phone|smartphone|tablet|charger/i, ["cell phone", "mobile phone", "electronics", "computer", "department"]],
  [/camera|lens|tripod/i, ["camera", "photography", "electronics", "department"]],
  [/vacuum|washer|dryer|refrigerator|microwave/i, ["appliance", "home goods", "department", "electronics"]],
  [/chair|desk|table|sofa|couch|bed|mattress/i, ["furniture", "office furniture", "home goods", "department"]],
  [/book|novel|textbook/i, ["book", "stationery", "department"]], [/toy|lego|doll|game/i, ["toy", "game", "hobby", "department"]], [/shirt|jacket|dress|jeans|clothing|pants/i, ["clothing", "fashion", "department"]],
];
const nonRetail = /repair service|museum|tourist attraction|consultant|contractor|school|university|doctor|clinic|hospital|hotel|lawyer|accountant|real estate|software company|manufacturer/i;
const generalRetail = /store|shop|retailer|market|mall|department|supermarket|pharmacy|hardware|supply/i;
const excludedHosts = /(?:amazon|ebay|etsy|facebook|pinterest|aliexpress|temu|wikipedia)\./i;
const countries = new Map([["israel", "IL"], ["united states", "US"], ["usa", "US"], ["canada", "CA"], ["united kingdom", "GB"], ["uk", "GB"], ["germany", "DE"], ["france", "FR"], ["italy", "IT"], ["spain", "ES"], ["australia", "AU"]]);

function logoDataUri(name) { const initial = String(name || "S").trim().charAt(0).toUpperCase(); return `data:image/svg+xml,${encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><rect width="64" height="64" rx="12" fill="#eef8f8"/><text x="32" y="41" text-anchor="middle" font-family="Arial" font-size="30" font-weight="700" fill="#007b83">${initial.replace(/[<>&]/g, "")}</text></svg>`)}`; }
export function safeHttpUrl(value, fallback = "") { try { const parsed = new URL(String(value ?? "")); return ["https:", "http:"].includes(parsed.protocol) ? parsed.href : fallback; } catch { return fallback; } }
export function shortRetailerName(value) { return String(value || "Retailer").split(/\s(?:[-–—|·]|:\s)\s/)[0].replace(/\s+(?:ישראל(?:\s+אתר\s+היבואן\s+הרשמי)?|אתר\s+היבואן\s+הרשמי|היבואן\s+הרשמי|official\s+(?:site|store)|israel)$/iu, "").trim() || "Retailer"; }
function rulesFor(query) { return productRules.find((group) => group.match.test(query))?.rules ?? []; }
function attributesFor(query, text, condition, merchant) { const attributes = { condition, retailer: shortRetailerName(merchant) }; const specific = rulesFor(query); for (const rule of specific) { const value = rule.infer ? rule.infer(text) : inferValue(text, rule.values); if (value) attributes[rule.id] = value; } if (!specific.some((rule) => rule.id === "color")) { const value = inferValue(text, colors); if (value) attributes.color = value; } if (!specific.some((rule) => rule.id === "material")) { const value = inferValue(text, materials); if (value) attributes.material = value; } if (!specific.some((rule) => rule.id === "features")) { const value = inferValue(text, features); if (value) attributes.features = value; } return attributes; }
function used(item) { return /used|pre.?owned|refurb|renewed|open box|vintage|second.?hand|mercari|poshmark|offerup|back market/i.test(`${item.title ?? ""} ${item.condition ?? ""} ${item.badge ?? ""} ${item.source ?? ""}`); }
function local(item) { return /(?:store|curbside|local)\s+pickup|pick\s*up\s+(?:today|in store)|in-store pickup/i.test(`${item.delivery ?? ""} ${(item.extensions ?? []).join(" ")}`); }
function validCoordinates(value) { const lat = Number(value?.lat), lon = Number(value?.lon); return Number.isFinite(lat) && Number.isFinite(lon) && Math.abs(lat) <= 90 && Math.abs(lon) <= 180 ? { lat, lon } : null; }
function distanceMiles(origin, point) { const destination = validCoordinates(point); if (!origin || !destination) return undefined; const rad = (value) => value * Math.PI / 180, dLat = rad(destination.lat - origin.lat), dLon = rad(destination.lon - origin.lon); const a = Math.sin(dLat / 2) ** 2 + Math.cos(rad(origin.lat)) * Math.cos(rad(destination.lat)) * Math.sin(dLon / 2) ** 2; return 3958.8 * 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a)); }
function relevance(place, query, origin) { const type = String(place.type ?? "").toLowerCase(), text = `${place.title ?? ""} ${type}`.toLowerCase(), distance = distanceMiles(origin, place.gps_coordinates ? { lat: place.gps_coordinates.latitude, lon: place.gps_coordinates.longitude } : null); if ((distance !== undefined && distance > 50) || (nonRetail.test(type) && !generalRetail.test(type))) return -Infinity; let score = generalRetail.test(type) ? 2 : 0; const rule = storeRules.find(([match]) => match.test(query)); if (rule) { const matches = rule[1].filter((value) => text.includes(value)).length; if (!matches) return -Infinity; score += matches * 4; } return score + (place.website ? 1 : 0) + (distance === undefined ? 0 : Math.max(0, 2 - distance / 10)); }
function shippingFor(item, itemPrice) { const text = `${item.delivery ?? ""} ${(item.extensions ?? []).join(" ")}`; if (/free (delivery|shipping)/i.test(text)) return { shippingPrice: 0, totalPrice: itemPrice, shippingEstimated: false }; const match = text.match(/(?:shipping|delivery)[^$]*\$([0-9]+(?:\.[0-9]{1,2})?)/i); const shippingPrice = match ? number(match[1]) : null; return { shippingPrice, totalPrice: itemPrice !== null && shippingPrice !== null ? itemPrice + shippingPrice : itemPrice, shippingEstimated: shippingPrice !== null }; }
function countryCode(location) { const text = String(location ?? "").toLowerCase(); for (const [name, code] of countries) if (text.includes(name)) return code; return null; }
async function fetchJson(url, options = {}, timeoutMs = 10000) { const controller = new AbortController(), timer = setTimeout(() => controller.abort(), timeoutMs); try { const response = await fetch(url, { ...options, signal: controller.signal }); if (!response.ok) throw new Error(`Provider returned ${response.status}`); const data = await response.json(); if (data.error) throw new Error(data.error); return data; } finally { clearTimeout(timer); } }

async function ebayAccess(credentials) { if (!credentials?.clientId || !credentials?.clientSecret) return null; if (ebayToken?.expiresAt > Date.now() + 60000) return ebayToken.value; const basic = Buffer.from(`${credentials.clientId}:${credentials.clientSecret}`).toString("base64"); const data = await fetchJson("https://api.ebay.com/identity/v1/oauth2/token", { method: "POST", headers: { Authorization: `Basic ${basic}`, "Content-Type": "application/x-www-form-urlencoded" }, body: new URLSearchParams({ grant_type: "client_credentials", scope: "https://api.ebay.com/oauth/api_scope" }) }); ebayToken = { value: data.access_token, expiresAt: Date.now() + (number(data.expires_in) ?? 7200) * 1000 }; return data.access_token; }
async function ebaySearch(query, location, credentials) { const token = await ebayAccess(credentials); if (!token) return []; const country = countryCode(location), filters = ["conditions:{USED}"]; if (country) filters.push(`deliveryCountry:${country}`); const params = new URLSearchParams({ q: query, limit: "15", filter: filters.join(",") }), headers = { Authorization: `Bearer ${token}`, "X-EBAY-C-MARKETPLACE-ID": "EBAY_US" }; if (country) headers["X-EBAY-C-ENDUSERCTX"] = `contextualLocation=country=${country}`; const data = await fetchJson(`https://api.ebay.com/buy/browse/v1/item_summary/search?${params}`, { headers }, 8000); return (data.itemSummaries ?? []).map((item, index) => { const price = item.price, shipping = item.shippingOptions?.[0]?.shippingCost, itemPrice = number(price?.convertedFromCurrency === "USD" ? price.convertedFromValue : price?.value), shippingPrice = number(shipping?.convertedFromCurrency === "USD" ? shipping.convertedFromValue : shipping?.value), totalPrice = itemPrice !== null && shippingPrice !== null ? itemPrice + shippingPrice : itemPrice, condition = item.condition || "Used", merchant = item.seller?.username ? `eBay · ${item.seller.username}` : "eBay"; return { id: `ebay-${item.itemId ?? index}`, category: "secondHand", merchant, merchantLogoUrl: "/ebay.svg", title: item.title || "Pre-owned eBay listing", subtitle: [condition, item.itemLocation?.country].filter(Boolean).join(" · "), imageUrl: safeHttpUrl(item.image?.imageUrl || item.thumbnailImages?.[0]?.imageUrl), rating: number(item.seller?.feedbackPercentage) ? Math.min(5, number(item.seller.feedbackPercentage) / 20) : 0, reviewCount: number(item.seller?.feedbackScore) ?? 0, itemPrice, shippingPrice, totalPrice, currency: price?.convertedFromCurrency === "USD" ? "USD" : price?.currency || "USD", priceVerified: totalPrice !== null, availability: "Available on eBay", condition, attributes: attributesFor(query, item.title || "", condition, "eBay"), destinationUrl: safeHttpUrl(item.itemWebUrl, `https://www.ebay.com/sch/i.html?_nkw=${encodeURIComponent(query)}`), linkLabel: "View product" }; }); }
function shoppingOffer(item, index, query) { const itemPrice = number(item.extracted_price ?? item.price), shipping = shippingFor(item, itemPrice), isUsed = used(item), isLocal = !isUsed && local(item), merchant = item.source || item.merchant || item.seller || "Retailer", text = `${item.title ?? ""} ${(item.extensions ?? []).join(" ")}`, condition = isUsed ? (item.condition || (/refurb|renewed/i.test(text) ? "Refurbished" : "Used")) : "New"; return { id: `serp-${item.product_id ?? item.position ?? index}`, category: isUsed ? "secondHand" : isLocal ? "local" : "order", merchant, merchantLogoUrl: safeHttpUrl(item.source_icon || item.favicon, logoDataUri(merchant)), title: item.title || "Product offer", subtitle: (item.extensions ?? []).slice(0, 3).join(" · ") || item.delivery || "See retailer for product details", imageUrl: safeHttpUrl(item.thumbnail || item.image || item.favicon, logoDataUri(merchant)), rating: number(item.rating) ?? 0, reviewCount: number(item.reviews) ?? 0, itemPrice, shippingPrice: isLocal ? null : shipping.shippingPrice, totalPrice: isLocal ? itemPrice : shipping.shippingPrice !== null ? shipping.totalPrice : null, currency: "USD", shippingEstimated: shipping.shippingEstimated, priceVerified: itemPrice !== null && (isLocal || shipping.shippingPrice !== null), availability: isLocal ? "Check local stock" : "Available online", arrival: isLocal ? undefined : item.delivery, condition, attributes: attributesFor(query, text, condition, merchant), destinationUrl: safeHttpUrl(item.link || item.product_link, `https://www.google.com/search?tbm=shop&q=${encodeURIComponent(query)}`), linkLabel: "View product" }; }
function siteSearch(site, query) { try { return `https://www.google.com/search?q=${encodeURIComponent(`site:${new URL(site).hostname.replace(/^www\./, "")} ${query}`)}`; } catch { return `https://www.google.com/search?q=${encodeURIComponent(query)}`; } }
function mapOffer(place, index, query, origin) { const merchant = place.title || place.name || "Local store", itemPrice = number(place.extracted_price ?? place.product_price), point = place.gps_coordinates ? { lat: place.gps_coordinates.latitude, lon: place.gps_coordinates.longitude } : null; return { id: `local-${place.place_id ?? place.data_id ?? index}`, category: "local", merchant, merchantLogoUrl: safeHttpUrl(place.favicon, logoDataUri(merchant)), title: `${query} at ${merchant}`, subtitle: [place.type, place.address].filter(Boolean).join(" · ") || "Nearby store", imageUrl: safeHttpUrl(place.thumbnail || place.image, logoDataUri(merchant)), rating: number(place.rating) ?? 0, reviewCount: number(place.reviews) ?? 0, itemPrice, shippingPrice: null, totalPrice: itemPrice, currency: "USD", priceVerified: itemPrice !== null, availability: place.open_state || "Check product availability", distanceMiles: distanceMiles(origin, point), condition: "New", attributes: attributesFor(query, query, "New", merchant), destinationUrl: siteSearch(place.website || place.links?.website, query), linkLabel: "Find product" }; }
function localPrice(text, extracted) { const direct = number(extracted); if (direct !== null) return { value: direct, currency: /₪|NIS|ILS/i.test(text) ? "ILS" : "USD" }; const ils = text.match(/(?:₪|NIS|ILS)\s*([0-9][0-9,.]*)|([0-9][0-9,.]*)\s*(?:₪|NIS|ILS)/i); if (ils) return { value: number(ils[1] ?? ils[2]), currency: "ILS" }; const usd = text.match(/\$\s*([0-9][0-9,.]*)/); return usd ? { value: number(usd[1]), currency: "USD" } : { value: null, currency: "USD" }; }
function localProduct(item, index, query, location) { const link = safeHttpUrl(item.link); if (!link) return null; const url = new URL(link); if (excludedHosts.test(url.hostname) || url.pathname === "/") return null; const text = `${item.title ?? ""} ${item.snippet ?? ""} ${(item.rich_snippet?.top?.extensions ?? []).join(" ")}`, city = String(location).split(",")[0].trim().toLowerCase(); if (!/\.co\.il$/i.test(url.hostname) && !/₪|NIS|ILS/i.test(text) && !(city && text.toLowerCase().includes(city))) return null; const price = localPrice(text, item.extracted_price); if (price.value === null) return null; const merchant = shortRetailerName(item.source || item.displayed_link?.split(" › ")[0] || url.hostname.replace(/^www\./, "").split(".")[0]); return { id: `local-product-${index}-${url.hostname}`, category: "local", merchant, merchantLogoUrl: safeHttpUrl(item.favicon, logoDataUri(merchant)), title: item.title?.split(/\s[-|–—]\s/)[0] || `${query} at ${merchant}`, subtitle: String(item.snippet ?? "").slice(0, 150) || `Available near ${location}`, imageUrl: safeHttpUrl(item.thumbnail || item.image || item.favicon, logoDataUri(merchant)), rating: 0, reviewCount: 0, itemPrice: price.value, shippingPrice: null, totalPrice: price.value, currency: price.currency, priceVerified: true, availability: "Price found on product page", condition: "New", attributes: attributesFor(query, text, "New", merchant), destinationUrl: link, linkLabel: "View product" }; }

export function buildFacets(offers, query) { const specific = rulesFor(query).map((rule) => [rule.id, rule.label]), specificIds = new Set(specific.map(([id]) => id)), definitions = [["condition", "Condition"], ...specific, ["retailer", "Retailer"], ["color", "Color"], ...(!specificIds.has("material") ? [["material", "Material"]] : []), ...(!specificIds.has("features") ? [["features", "Features"]] : [])], unique = definitions.filter(([id], index) => definitions.findIndex(([other]) => other === id) === index); return unique.map(([id, label]) => { const counts = new Map(); let covered = 0; for (const offer of offers) { const value = offer.attributes[id]; if (value) { covered++; counts.set(value, (counts.get(value) ?? 0) + 1); } } const coverage = specificIds.has(id) ? .05 : id === "retailer" || id === "condition" ? .1 : .2; if (counts.size < 2 || covered < Math.max(2, Math.ceil(offers.length * coverage))) return null; return { id, label, options: [...counts].sort((a, b) => b[1] - a[1]).slice(0, 10).map(([value, count]) => ({ value, count })) }; }).filter(Boolean); }
function makeResult(query, offers) { const seen = new Set(), clean = offers.filter((offer) => offer?.title && !seen.has(`${offer.category}|${offer.destinationUrl}`) && seen.add(`${offer.category}|${offer.destinationUrl}`)).slice(0, 45); return { query, resultCount: clean.length, offers: clean, facets: buildFacets(clean, query), source: "live" }; }
async function shoppingSearch(query, location, key) { const params = new URLSearchParams({ engine: "google_shopping", q: query, api_key: key, hl: "en", num: "40" }); if (location && location !== "Current location") params.set("location", location); const data = await fetchJson(`https://serpapi.com/search.json?${params}`, {}, 8000); return [...(data.shopping_results ?? []), ...(data.inline_shopping_results ?? [])].map((item, index) => shoppingOffer(item, index, query)); }
async function mapsSearch(query, location, key, coordinates) { const origin = validCoordinates(coordinates); if (!origin && (!location || location === "Current location")) return []; const params = new URLSearchParams({ engine: "google_maps", type: "search", q: origin ? `where to buy ${query}` : `where to buy ${query} near ${location}`, api_key: key, hl: "en" }); if (origin) params.set("ll", `@${origin.lat},${origin.lon},14z`); const data = await fetchJson(`https://serpapi.com/search.json?${params}`, {}, 8000); return (data.local_results ?? []).map((place, index) => ({ place, index, score: relevance(place, query, origin) })).filter(({ score }) => Number.isFinite(score) && score >= 2).sort((a, b) => b.score - a.score).slice(0, 10).map(({ place, index }) => mapOffer(place, index, query, origin)); }
async function localProductSearch(query, location, key) { if (!location || location === "Current location") return []; const params = new URLSearchParams({ engine: "google", q: `${query} price near ${location}`, api_key: key, hl: "en", num: "20" }), data = await fetchJson(`https://serpapi.com/search.json?${params}`, {}, 11000); return (data.organic_results ?? []).map((item, index) => localProduct(item, index, query, location)).filter(Boolean).slice(0, 12); }
async function runScope(scope, query, location, key, coordinates, credentials) { if (scope === "online") { const [shopping, ebay] = await Promise.allSettled([shoppingSearch(query, location, key), ebaySearch(query, location, credentials)]); if (shopping.status === "rejected" && ebay.status === "rejected") throw shopping.reason; const offers = shopping.status === "fulfilled" ? shopping.value : []; return makeResult(query, [...offers.filter((offer) => offer.category === "order").slice(0, 22), ...(ebay.status === "fulfilled" ? ebay.value : []), ...offers.filter((offer) => offer.category === "secondHand")]); } if (scope === "local") return makeResult(query, await mapsSearch(query, location, key, coordinates)); if (scope === "local-products") return makeResult(query, await localProductSearch(query, location, key)); const all = await Promise.allSettled([shoppingSearch(query, location, key), mapsSearch(query, location, key, coordinates), localProductSearch(query, location, key), ebaySearch(query, location, credentials)]); if (all.every(({ status }) => status === "rejected")) throw all[0].reason; const shopping = all[0].status === "fulfilled" ? all[0].value : []; return makeResult(query, [...(all[2].status === "fulfilled" ? all[2].value : []), ...(all[1].status === "fulfilled" ? all[1].value : []), ...shopping.filter((offer) => offer.category === "local"), ...shopping.filter((offer) => offer.category === "order"), ...(all[3].status === "fulfilled" ? all[3].value : []), ...shopping.filter((offer) => offer.category === "secondHand")]); }
export async function searchCatalog(query, location, apiKey, coordinates, credentials, scope = "all") { if (!apiKey) throw new Error("SERPAPI_API_KEY is not configured"); const safeScope = ["all", "online", "local", "local-products"].includes(scope) ? scope : "all", point = validCoordinates(coordinates), cacheKey = `${safeScope}|${query.trim().toLowerCase()}|${String(location || "").trim().toLowerCase()}|${point ? `${point.lat.toFixed(4)},${point.lon.toFixed(4)}` : ""}`; const cached = cache.get(cacheKey); if (cached && Date.now() - cached.at < CACHE_MS) return cached.value; if (inFlight.has(cacheKey)) return inFlight.get(cacheKey); const request = runScope(safeScope, query.trim(), location, apiKey, point, credentials).then((value) => { cache.set(cacheKey, { at: Date.now(), value }); return value; }).finally(() => inFlight.delete(cacheKey)); inFlight.set(cacheKey, request); return request; }
