import { useState } from "react";
import { ChevronDown, X } from "lucide-react";
import type { Facet } from "../types";
import { displayDistance, type DistanceUnit } from "../services/distance";

type Props = { facets: Facet[]; selected: Record<string, string[]>; distance: number; distanceUnit: DistanceUnit; priceMin: string; priceMax: string; currency?: string; mobile?: boolean; onToggle: (facet: string, value: string) => void; onDistance: (value: number) => void; onPriceMin: (value: string) => void; onPriceMax: (value: string) => void; onClear: () => void; onClose?: () => void; };
export function FilterPanel({ facets, selected, distance, distanceUnit, priceMin, priceMax, currency = "USD", mobile, onToggle, onDistance, onPriceMin, onPriceMax, onClear, onClose }: Props) {
  const [collapsed, setCollapsed] = useState<Record<string, boolean>>({});
  const toggleSection = (id: string) => setCollapsed((current) => ({ ...current, [id]: !current[id] }));
  return <aside className={mobile ? "filters filters--mobile" : "filters"} aria-label="Product filters">
    <div className="filters__header"><strong>Filters</strong><button type="button" className="text-button" onClick={onClear}>Clear all</button>{mobile && <button type="button" className="icon-button" onClick={onClose} aria-label="Close filters"><X size={21} /></button>}</div>
    <div className="filter-scroll">{facets.map((facet) => <fieldset className="facet" key={facet.id}><legend className="sr-only">{facet.label}</legend><button type="button" className="facet__title" aria-expanded={!collapsed[facet.id]} onClick={() => toggleSection(facet.id)}><span>{facet.label}</span><ChevronDown size={16} /></button>{!collapsed[facet.id] && facet.options.map((option) => { const checked = selected[facet.id]?.includes(option.value) ?? false; return <label className="checkbox-row" key={option.value}><input type="checkbox" checked={checked} onChange={() => onToggle(facet.id, option.value)} /><span>{option.value}</span><small>{option.count}</small></label>; })}</fieldset>)}
      <fieldset className="facet facet--distance"><legend className="sr-only">Distance</legend><button type="button" className="facet__title" aria-expanded={!collapsed.__distance} onClick={() => toggleSection("__distance")}><span>Distance</span><ChevronDown size={16} /></button>{!collapsed.__distance && <><input aria-label="Maximum distance" type="range" min="1" max="50" value={distance} onChange={(event) => onDistance(Number(event.target.value))} /><div className="range-labels"><span>{displayDistance(1, distanceUnit)}</span><span>{displayDistance(distance, distanceUnit)}</span></div></>}</fieldset>
      <fieldset className="facet"><legend className="sr-only">Total price</legend><button type="button" className="facet__title" aria-expanded={!collapsed.__totalPrice} onClick={() => toggleSection("__totalPrice")}><span>Total price</span><ChevronDown size={16} /></button>{!collapsed.__totalPrice && <div className="price-inputs"><label>{new Intl.NumberFormat("en", { style: "currency", currency, currencyDisplay: "narrowSymbol", maximumFractionDigits: 0 }).format(0).replace(/[\d.,\s]/g, "")}<input aria-label="Minimum price" placeholder="Min" inputMode="decimal" value={priceMin} onChange={(event) => onPriceMin(event.target.value)} /></label><label>{new Intl.NumberFormat("en", { style: "currency", currency, currencyDisplay: "narrowSymbol", maximumFractionDigits: 0 }).format(0).replace(/[\d.,\s]/g, "")}<input aria-label="Maximum price" placeholder="Max" inputMode="decimal" value={priceMax} onChange={(event) => onPriceMax(event.target.value)} /></label></div>}</fieldset>
    </div>
  </aside>;
}
