import { ChevronDown, X } from "lucide-react";
import type { Facet } from "../types";

type Props = { facets: Facet[]; selected: Record<string, string[]>; showUnverified: boolean; distance: number; priceMin: string; priceMax: string; currency?: string; mobile?: boolean; onToggle: (facet: string, value: string) => void; onUnverified: (value: boolean) => void; onDistance: (value: number) => void; onPriceMin: (value: string) => void; onPriceMax: (value: string) => void; onClear: () => void; onClose?: () => void; };
export function FilterPanel({ facets, selected, showUnverified, distance, priceMin, priceMax, currency = "USD", mobile, onToggle, onUnverified, onDistance, onPriceMin, onPriceMax, onClear, onClose }: Props) {
  return <aside className={mobile ? "filters filters--mobile" : "filters"} aria-label="Product filters">
    <div className="filters__header"><strong>Filters</strong><button type="button" className="text-button" onClick={onClear}>Clear all</button>{mobile && <button type="button" className="icon-button" onClick={onClose} aria-label="Close filters"><X size={21} /></button>}</div>
    <div className="filter-scroll">{facets.map((facet) => <fieldset className="facet" key={facet.id}><legend className="sr-only">{facet.label}</legend><div className="facet__title" aria-hidden="true">{facet.label}<ChevronDown size={15} /></div>{facet.options.map((option) => { const checked = selected[facet.id]?.includes(option.value) ?? false; return <label className="checkbox-row" key={option.value}><input type="checkbox" checked={checked} onChange={() => onToggle(facet.id, option.value)} /><span>{option.value}</span><small>{option.count}</small></label>; })}</fieldset>)}
      <fieldset className="facet facet--distance"><legend className="sr-only">Distance</legend><div className="facet__title" aria-hidden="true">Distance<ChevronDown size={15} /></div><input aria-label="Maximum distance" type="range" min="1" max="50" value={distance} onChange={(event) => onDistance(Number(event.target.value))} /><div className="range-labels"><span>1 mile</span><span>{distance} miles</span></div></fieldset>
      <fieldset className="facet"><legend className="sr-only">Total price</legend><div className="facet__title" aria-hidden="true">Total price<ChevronDown size={15} /></div><div className="price-inputs"><label>{new Intl.NumberFormat("en", { style: "currency", currency, currencyDisplay: "narrowSymbol", maximumFractionDigits: 0 }).format(0).replace(/[\d.,\s]/g, "")}<input aria-label="Minimum price" placeholder="Min" inputMode="decimal" value={priceMin} onChange={(event) => onPriceMin(event.target.value)} /></label><label>{new Intl.NumberFormat("en", { style: "currency", currency, currencyDisplay: "narrowSymbol", maximumFractionDigits: 0 }).format(0).replace(/[\d.,\s]/g, "")}<input aria-label="Maximum price" placeholder="Max" inputMode="decimal" value={priceMax} onChange={(event) => onPriceMax(event.target.value)} /></label></div></fieldset>
      <label className="checkbox-row checkbox-row--unverified"><input type="checkbox" checked={showUnverified} onChange={(event) => onUnverified(event.target.checked)} /><span>Show offers with unverified prices</span></label>
    </div>
  </aside>;
}
