import { RefreshCcw, ShoppingCart, Store } from "lucide-react";
import type { Offer, OfferCategory } from "../types";

const labels: Record<OfferCategory, string> = { order: "Order online", local: "Buy in store", secondHand: "Second hand" };
function Stars({ rating }: { rating: number }) { const full = Math.round(rating); return <span className="stars" aria-label={`${rating} out of 5 stars`}>{"★".repeat(full)}{"☆".repeat(Math.max(0, 5 - full))}</span>; }
function logoFor(name: string) { const initial = name.trim().charAt(0).toUpperCase(); return `data:image/svg+xml,${encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><rect width="64" height="64" rx="12" fill="#eef8f8"/><text x="32" y="41" text-anchor="middle" font-family="Arial" font-size="30" font-weight="700" fill="#007b83">${initial}</text></svg>`)}`; }
function Price({ offer, category }: { offer: Offer; category: OfferCategory }) { if (!offer.priceVerified || offer.totalPrice === null || offer.itemPrice === null) return <span className="unverified-price">Price unverified</span>; return <div className="offer-price"><strong>${offer.totalPrice.toFixed(2)}</strong><small>${offer.itemPrice.toFixed(2)} item{category !== "local" && (offer.shippingPrice === 0 ? <> + <span className="free-shipping">Free shipping</span></> : offer.shippingPrice !== null ? <> + {offer.shippingEstimated ? "est. " : ""}${offer.shippingPrice.toFixed(2)} shipping</> : null)}</small></div>; }
export function OfferSection({ category, offers }: { category: OfferCategory; offers: Offer[] }) {
  if (!offers.length) return null; const Icon = category === "order" ? ShoppingCart : category === "local" ? Store : RefreshCcw;
  return <section className="offer-section" aria-labelledby={`category-${category}`}><h2 id={`category-${category}`}><Icon size={21} />{labels[category]} <span>({offers.length})</span></h2><div className="offer-table-heading" aria-hidden="true"><span>Offer</span><span>Retailer</span><span>Variant / Specs</span><span>Availability</span><span>Total price</span><span>Details</span></div><div className="offer-list">{offers.map((offer) => <article className="offer-row" key={offer.id}><img className="product-image" src={offer.imageUrl} alt="" loading="lazy" /><div className="offer-merchant"><div className="merchant-identity"><img src={offer.merchantLogoUrl ?? logoFor(offer.merchant)} alt="" /><a href={offer.destinationUrl} target="_blank" rel="noreferrer">{offer.merchant}</a></div>{offer.reviewCount > 0 && <span><Stars rating={offer.rating} /> <small>({offer.reviewCount.toLocaleString()})</small></span>}</div><div className="offer-specs"><strong>{offer.title}</strong><span>{offer.subtitle}</span>{offer.condition && <small>{offer.condition}</small>}</div><div className="offer-availability"><strong>{offer.availability}</strong>{category === "local" && <span className="pickup-label">Local pickup</span>}{offer.arrival && <small>{offer.arrival}</small>}{offer.distanceMiles !== undefined && <small>{offer.distanceMiles.toFixed(1)} mi</small>}</div><Price offer={offer} category={category} /><a className="secondary-button offer-link" href={offer.destinationUrl} target="_blank" rel="noreferrer">View offer</a></article>)}</div></section>;
}
