import { ImageOff, RefreshCcw, ShoppingCart, Store } from "lucide-react";
import type { Offer, OfferCategory } from "../types";

const labels: Record<OfferCategory, string> = { order: "Order online", local: "Buy in store", secondHand: "Second hand" };
function Stars({ rating }: { rating: number }) { const full = Math.round(rating); return <span className="stars" aria-label={`${rating} out of 5 stars`}>{"★".repeat(full)}{"☆".repeat(Math.max(0, 5 - full))}</span>; }
function money(value: number, currency = "USD") { try { return new Intl.NumberFormat("en-US", { style: "currency", currency, maximumFractionDigits: currency === "ILS" ? 0 : 2 }).format(value); } catch { return `${value.toFixed(2)} ${currency}`; } }
function Price({ offer, category }: { offer: Offer; category: OfferCategory }) { if (!offer.priceVerified || offer.totalPrice === null || offer.itemPrice === null) return <span className="unverified-price">Price not found</span>; return <div className="offer-price"><strong>{money(offer.totalPrice, offer.currency)}</strong><small>{money(offer.itemPrice, offer.currency)} item{category !== "local" && (offer.shippingPrice === 0 ? <> + <span className="free-shipping">Free shipping</span></> : offer.shippingPrice !== null ? <> + {offer.shippingEstimated ? "est. " : ""}{money(offer.shippingPrice, offer.currency)} shipping</> : null)}</small></div>; }
export function OfferSection({ category, offers }: { category: OfferCategory; offers: Offer[] }) {
  if (!offers.length) return null; const Icon = category === "order" ? ShoppingCart : category === "local" ? Store : RefreshCcw;
  return <section className="offer-section" aria-labelledby={`category-${category}`}><h2 id={`category-${category}`}><Icon size={21} />{labels[category]} <span>({offers.length})</span></h2><div className="offer-table-heading" aria-hidden="true"><span>Offer</span><span>Retailer</span><span>Variant / Specs</span><span>Availability</span><span>Total price</span><span>Details</span></div><div className="offer-list">{offers.map((offer) => <article className="offer-row" key={offer.id}>{offer.imageUrl ? <img className="product-image" src={offer.imageUrl} alt="" loading="lazy" /> : <div className="product-image product-image--empty" aria-label="No product image available"><ImageOff size={22} /></div>}<div className="offer-merchant"><div className="merchant-identity">{offer.merchantLogoUrl && <img src={offer.merchantLogoUrl} alt="" />}<a href={offer.destinationUrl} target="_blank" rel="noreferrer">{offer.merchant}</a></div>{offer.reviewCount > 0 && <span><Stars rating={offer.rating} /> <small>({offer.reviewCount.toLocaleString()})</small></span>}</div><div className="offer-specs"><strong>{offer.title}</strong><span>{offer.subtitle}</span>{offer.condition && <small>{offer.condition}</small>}</div><div className="offer-availability"><strong>{offer.availability}</strong>{category === "local" && <span className="pickup-label">Local pickup</span>}{offer.arrival && <small>{offer.arrival}</small>}{offer.distanceMiles !== undefined && <small>{offer.distanceMiles.toFixed(1)} mi</small>}</div><Price offer={offer} category={category} /><a className="secondary-button offer-link" href={offer.destinationUrl} target="_blank" rel="noreferrer">{offer.linkLabel ?? "View product"}</a></article>)}</div></section>;
}
